CREATE DATABASE IF NOT EXISTS ATM_MoneyChecker;
USE ATM_MoneyChecker;

CREATE TABLE IF NOT EXISTS BANK (
  BankID INT AUTO_INCREMENT PRIMARY KEY,
  BankName VARCHAR(120) NOT NULL UNIQUE,
  BranchCode VARCHAR(40) NOT NULL,
  HeadOfficeLocation VARCHAR(180) NOT NULL,
  CashCapacity INT NOT NULL DEFAULT 0,
  CHECK (CashCapacity >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS STATUS_LOOKUP (
  StatusID INT AUTO_INCREMENT PRIMARY KEY,
  StatusDescription VARCHAR(60) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `USER` (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(140) NOT NULL UNIQUE,
  Phone_no VARCHAR(20) NOT NULL,
  ReliabilityScore INT NOT NULL DEFAULT 0,
  BadgeLevel VARCHAR(20) NOT NULL DEFAULT 'Bronze',
  CHECK (ReliabilityScore >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ATM (
  ATMId INT AUTO_INCREMENT PRIMARY KEY,
  Pincode VARCHAR(10) NOT NULL,
  WheelChairAccess TINYINT(1) NOT NULL DEFAULT 0,
  SecurityGuard TINYINT(1) NOT NULL DEFAULT 0,
  BankID INT NOT NULL,
  StatusID INT NOT NULL,
  Latitude DECIMAL(10, 8) NOT NULL,
  Longitude DECIMAL(11, 8) NOT NULL,
  PlaceID VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT fk_atm_bank FOREIGN KEY (BankID) REFERENCES BANK(BankID),
  CONSTRAINT fk_atm_status FOREIGN KEY (StatusID) REFERENCES STATUS_LOOKUP(StatusID),
  INDEX idx_atm_pincode (Pincode),
  INDEX idx_atm_geo (Latitude, Longitude)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS REPORT (
  ReportID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ATMId INT NOT NULL,
  UserID INT NOT NULL,
  Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CashLevel ENUM('Full', 'Partial', 'Empty', 'Unknown') NOT NULL DEFAULT 'Unknown',
  CONSTRAINT fk_report_atm FOREIGN KEY (ATMId) REFERENCES ATM(ATMId) ON DELETE CASCADE,
  CONSTRAINT fk_report_user FOREIGN KEY (UserID) REFERENCES `USER`(UserID) ON DELETE CASCADE,
  INDEX idx_report_atm_time (ATMId, Timestamp DESC),
  INDEX idx_report_user (UserID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ATM_SERVICES (
  ATMId INT NOT NULL,
  ServiceName VARCHAR(80) NOT NULL,
  Deposit TINYINT(1) NOT NULL DEFAULT 0,
  Printers TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (ATMId, ServiceName),
  CONSTRAINT fk_services_atm FOREIGN KEY (ATMId) REFERENCES ATM(ATMId) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT IGNORE INTO STATUS_LOOKUP (StatusDescription)
VALUES ('Working'), ('Partial/Low Cash'), ('Out of Service');
